[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AdaptFM"
version = "0.1.0"
description = "An Interactive Framework for Empirical Evaluation and Fine-Tuning of Foundation & Deep Learning Models in 3D Biological Imaging"
readme = "README.md"
requires-python = ">=3.13"


dependencies = ["napari",
                "tifffile",
                "dask[array]",
                "SimpleITK",
                "qtpy",
                "PyQt5",
                "magicgui",
                "torch",
                "Pillow",
                "scipy",
                "scikit-image",
                "kneed",
                "joblib",
                "pandas",
                "matplotlib",
                "zarr"]

[project.optional-dependencies]
sam2 = []   # submodule handles it, this just signals intent
sam3 = []

[project.scripts]
adaptfm-install-sam2 = "adaptfm.utils.install:install_sam2"
adaptfm-install-sam3 = "adaptfm.utils.install:install_sam3"

[tool.setuptools.packages.find]
where = ["."]
