[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AdaptFM"
version = "0.1.0"
description = "An Interactive Framework for Empirical Evaluation and Fine-Tuning of Foundation & Deep Learning Models in 3D Biological Imaging"
readme = "README.md"
requires-python = ">=3.12"


dependencies = ["napari",
                "tifffile",
                "dask[array]",
                "SimpleITK",
                "qtpy",
                "PyQt6",
                "magicgui",
                "Pillow",
                "scipy",
                "scikit-image>=0.26",
                "kneed",
                "joblib",
                "pandas",
                "matplotlib",
                "zarr",
                "numpy<2",
                "setuptools<82",]

[project.optional-dependencies]
sam2 = []   # submodule handles it, this just signals intent
sam3 = []

[project.scripts]

adaptfm-set-pytorch    = "AdaptFM.install.set_pytorch:main"

adaptfm-install-sam2 = "AdaptFM.model.model_utils:install_sam2"
adaptfm-install-sam3 = "AdaptFM.model.model_utils:install_sam3"
adaptfm-install-microsam = "AdaptFM.install.install_microsam:main"
adaptfm-install-cellposesam = "AdaptFM.install.install_cellposesam:main"
adaptfm-install-nnunet = "AdaptFM.install.install_nnunet:main"
adaptfm-install-sammed3d = "AdaptFM.install.install_sammed3d:main"
adaptfm-install-cellsam = "AdaptFM.install.install_cellsam:main"
adaptfm-install-useg = "AdaptFM.install.install_useg3d:main"
adaptfm-install-merlin ="AdaptFM.install.install_merlin:main"
adaptfm-install-bmex = "AdaptFM.install.install_bmex:main"
adaptfm-install-3dcellcompose = "AdaptFM.install.install_3dcellcompose:main"
adaptfm-install-ctfm ="AdaptFM.install.install_ctfm:main"
adaptfm-install-ssvt = "AdaptFM.install.install_ssvt:install_ssvt"
adaptfm-uninstall = "AdaptFM.install.uninstall_general:main"
adaptfm-uninstall-sam2 = "AdaptFM.install.uninstall_sam:uninstall_sam2"
adaptfm-uninstall-sam3 = "AdaptFM.install.uninstall_sam:uninstall_sam3"
adaptfm-uninstall-ssvt = "AdaptFM.install.install_ssvt:uninstall_ssvt"


[tool.setuptools.packages.find]
where = ["."]
